- ros_topic_name: "/autonomous_vehicle/cmd_vel"
  gz_topic_name: "/model/autonomous_vehicle/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/autonomous_vehicle/left_camera/image"
  gz_topic_name: "/world/empty/model/autonomous_vehicle/link/base_link/sensor/left_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/autonomous_vehicle/right_camera/image"
  gz_topic_name: "/world/empty/model/autonomous_vehicle/link/base_link/sensor/right_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/autonomous_vehicle/front_left_wheel_steering_joint/cmd_pos"
  gz_topic_name: "/model/autonomous_vehicle/joint/front_left_wheel_steering_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/autonomous_vehicle/front_right_wheel_steering_joint/cmd_pos"
  gz_topic_name: "/model/autonomous_vehicle/joint/front_right_wheel_steering_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/autonomous_vehicle/rear_left_wheel_joint/cmd_vel"
  gz_topic_name: "/model/autonomous_vehicle/joint/rear_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/autonomous_vehicle/rear_right_wheel_joint/cmd_vel"
  gz_topic_name: "/model/autonomous_vehicle/joint/rear_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/autonomous_vehicle/joint_state"
  gz_topic_name: "/world/empty/model/autonomous_vehicle/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/autonomous_vehicle/odometry"
  gz_topic_name: "/model/autonomous_vehicle/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS