- ros_topic_name: "/autonomous_vehicle/cmd_vel"
  gz_topic_name: "/model/autonomous_vehicle/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/left_camera/image"
  gz_topic_name: "/world/empty/model/autonomous_vehicle/link/left_camera_link/sensor/left_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: BIDIRECTIONAL
  
- ros_topic_name: "/right_camera/image"
  gz_topic_name: "/world/empty/model/autonomous_vehicle/link/right_camera_link/sensor/right_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: BIDIRECTIONAL
