%YAML:1.0
---
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 591.3193359375, 0., 384.,
          0., 591.3193531036377, 216.,
          0., 0., 1. ]
dist_coeffs: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [ 0., 0., 0., 0., 0. ]
